var searchData=
[
  ['client_5faddress_3',['client_address',['../classsensor__simulation_1_1Sensor.html#ad9e6ac7391e0e1fc214cfb5251def0af',1,'sensor_simulation::Sensor']]],
  ['client_5fcallback_5fgroup_5f_4',['client_callback_group_',['../classmachina_1_1client_1_1ndof__sensor__driver_1_1MachinaNDofSensorDriverClient.html#a12897150a2f05993ba1716a7a5486849',1,'machina::client::ndof_sensor_driver::MachinaNDofSensorDriverClient']]],
  ['closeconnection_5',['CloseConnection',['../classmachina_1_1tcp__interface_1_1TcpInterface.html#ad8bb50a09d971308bdb5ba34688e7f95',1,'machina::tcp_interface::TcpInterface']]],
  ['cmake_5fminimum_5frequired_6',['cmake_minimum_required',['../machina__ndof__sensor__driver__client_2CMakeLists_8txt.html#abf0ca310c0781bf34be12aeb894ad975',1,'cmake_minimum_required(VERSION 3.8) project(machina_ndof_sensor_driver_client) if(NOT CMAKE_C_STANDARD) set(CMAKE_C_STANDARD 99) endif() if(NOT CMAKE_CXX_STANDARD) set(CMAKE_CXX_STANDARD 17) endif() if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES &quot;Clang&quot;) add_compile_options(-Wall -Wextra -Wpedantic) endif() option(ENABLE_LOCKFREE &quot;Enable lock free data structures&quot; OFF) if(ENABLE_LOCKFREE) add_compile_definitions(ENABLE_LOCKFREE) endif() find_package(ament_cmake_auto REQUIRED) ament_auto_find_build_dependencies(REQUIRED $:&#160;CMakeLists.txt'],['../machina__ndof__sensor__driver__msgs_2CMakeLists_8txt.html#acafc9a79401aab1a8d1651907b39ba7f',1,'cmake_minimum_required(VERSION 3.8) project(machina_ndof_sensor_driver_msgs) if(NOT CMAKE_C_STANDARD) set(CMAKE_C_STANDARD 99) endif() if(NOT CMAKE_CXX_STANDARD) set(CMAKE_CXX_STANDARD 17) endif() if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES &quot;Clang&quot;) add_compile_options(-Wall -Wextra -Wpedantic) endif() find_package(ament_cmake_auto REQUIRED) ament_auto_find_build_dependencies(REQUIRED $:&#160;CMakeLists.txt'],['../machina__ndof__sensor__driver__service_2CMakeLists_8txt.html#a56390cb4da069f7aa47d49dcb96b2b59',1,'cmake_minimum_required(VERSION 3.8) project(machina_ndof_sensor_driver_service) if(NOT CMAKE_C_STANDARD) set(CMAKE_C_STANDARD 99) endif() if(NOT CMAKE_CXX_STANDARD) set(CMAKE_CXX_STANDARD 17) endif() if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES &quot;Clang&quot;) add_compile_options(-Wall -Wextra -Wpedantic) endif() option(ENABLE_LOCKFREE &quot;Enable lock free data structures&quot; OFF) if(ENABLE_LOCKFREE) add_compile_definitions(ENABLE_LOCKFREE) endif() find_package(ament_cmake_auto REQUIRED) ament_auto_find_build_dependencies(REQUIRED $:&#160;CMakeLists.txt'],['../machina__tcp__interface_2CMakeLists_8txt.html#ad0460f4178502196cf52967cd6e1eb29',1,'cmake_minimum_required(VERSION 3.8) project(machina_tcp_interface) if(NOT CMAKE_C_STANDARD) set(CMAKE_C_STANDARD 99) endif() if(NOT CMAKE_CXX_STANDARD) set(CMAKE_CXX_STANDARD 17) endif() if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES &quot;Clang&quot;) add_compile_options(-Wall -Wextra -Wpedantic) endif() find_package(ament_cmake_auto REQUIRED) ament_auto_find_build_dependencies(REQUIRED $:&#160;CMakeLists.txt']]],
  ['cmakelists_2etxt_7',['CMakeLists.txt',['../machina__ndof__sensor__driver_2CMakeLists_8txt.html',1,'(Global Namespace)'],['../machina__ndof__sensor__driver__client_2CMakeLists_8txt.html',1,'(Global Namespace)'],['../machina__ndof__sensor__driver__msgs_2CMakeLists_8txt.html',1,'(Global Namespace)'],['../machina__ndof__sensor__driver__service_2CMakeLists_8txt.html',1,'(Global Namespace)'],['../machina__ndof__sensor__driver__system__tests_2CMakeLists_8txt.html',1,'(Global Namespace)'],['../machina__tcp__interface_2CMakeLists_8txt.html',1,'(Global Namespace)']]],
  ['collection_5finterval_5f_8',['collection_interval_',['../classmachina_1_1client_1_1ndof__sensor__driver_1_1MachinaNDofSensorDriverClient.html#a5deeb9a735bc52117af985ad7f7b182b',1,'machina::client::ndof_sensor_driver::MachinaNDofSensorDriverClient']]],
  ['connect_9',['connect',['../classsensor__simulation_1_1Sensor.html#aec5141cf4c0461ebffc565327a6416a7',1,'sensor_simulation::Sensor']]],
  ['connected_10',['connected',['../classsensor__simulation_1_1Sensor.html#acce2b7e56a2a96f6cafd999f8d269f1a',1,'sensor_simulation::Sensor']]]
];
